### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by timbru31** [selenium-webdriver-in-practice/source#11]
Do you have any plans to publish this book other than https://leanpub.com/? (you know to get an ISBN, a real publisher name) etc.

I saw an old page on Manning, but it's stated that they are not gonna publish it.

---
Thanks for the offer to pay what you want on leanpub! 👍

**Comment by alexec** [comment]
Hi Tim,

This book can be downloaded from Amazon or iBooks. We just wanted to get it out there.

Alex
